# Generated by Django 4.2.7 on 2023-11-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_delete_datafiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='expense',
            field=models.BooleanField(default=True),
        ),
    ]
