# Generated by Django 4.2.7 on 2023-11-25 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('paytype', models.CharField(max_length=200)),
                ('payee', models.CharField(max_length=200)),
                ('purpose', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
    ]
