# Generated by Django 4.2.7 on 2023-11-25 04:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_data_file_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='file_date',
        ),
        migrations.AddField(
            model_name='data',
            name='file_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
