# Generated by Django 4.2.7 on 2023-11-25 05:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_data_file_date_data_file_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='file_timestamp',
        ),
        migrations.AddField(
            model_name='data',
            name='file_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
