# Generated by Django 4.2.7 on 2023-11-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_data_file_timestamp_data_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='amount_display',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
