# Generated by Django 4.2.7 on 2023-11-25 05:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_data_amount_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='file_upload_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
