# Generated by Django 4.2.7 on 2023-11-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_data_file_upload_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='file_upload_time',
            field=models.CharField(max_length=200),
        ),
    ]
