# Generated by Django 4.2.7 on 2023-11-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_data_file_upload_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ignore',
            field=models.BooleanField(default=False),
        ),
    ]
