# Generated by Django 4.2.7 on 2023-11-27 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_data_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
